# Generated by Django 3.1.5 on 2021-03-11 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FileCollector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=10)),
                ('extension', models.CharField(blank=True, max_length=5, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_file', models.BooleanField(default=False)),
                ('maxlength', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fo_asset_type',
            },
        ),
        migrations.CreateModel(
            name='WorkStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('desc', models.CharField(max_length=100)),
                ('json', models.JSONField(blank=True, default=list, null=True)),
                ('description', models.TextField(blank=True)),
                ('mode', models.CharField(choices=[('MAN', 'MANUAL'), ('FO', 'FormikoBot')], default='MAN', max_length=8)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fo_workstep',
            },
        ),

        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('value', models.CharField(blank=True, max_length=1000, null=True)),
                ('json', models.JSONField(blank=True, default=list, null=True)),
                ('source', models.CharField(choices=[('EXAU', 'External auto'), ('EXMA', 'External manual'), ('INAU', 'Internal auto'), ('INMA', 'Internal manual')], default='EXAU', max_length=15)),
                ('maxlength', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('assettype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FormikoBot.assettype')),
                ('client_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_owned_assets', to='FileCollector.client')),
                ('company_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_owned_assets', to='FileCollector.company')),
            ],
            options={
                'db_table': 'fo_asset',
            },
        ),
        migrations.CreateModel(
            name='AssetPreset',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='FormikoBot.asset')),
                ('title', models.CharField(max_length=30)),
                ('pres_description', models.TextField(blank=True, null=True)),
                ('pres_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fo_asset_preset',
                'ordering': ['title', 'name', 'value'],
            },
            bases=('FormikoBot.asset',),
        ),
    ]
