# Generated by Django 3.1.6 on 2021-05-17 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FormikoBot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['-pk']},
        ),
    ]
