# Generated by Django 3.1.6 on 2021-05-24 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FileCollector', '0023_video_size'),
        ('FormikoBot', '0002_auto_20210517_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('starttime', models.DateTimeField(blank=True, null=True)),
                ('endtime', models.DateTimeField(blank=True, null=True)),
                ('runtime', models.IntegerField(blank=True, null=True)),
                ('mode', models.CharField(choices=[('MAN', 'MANUAL'), ('BOT', 'FormikoBot')], default='MAN', max_length=8)),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('ACTIVE', 'ACTIVE'), ('FAILED', 'FAILED'), ('COMPLETE', 'COMPLETE')], default='OPEN', max_length=8)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to='FileCollector.client')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='FileCollector.client')),
            ],
            options={
                'db_table': 'fo_task',
            },
        ),
    ]
