# Generated by Django 3.1.6 on 2021-05-24 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FormikoBot', '0005_auto_20210524_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskPreset',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='FormikoBot.task')),
                ('title', models.CharField(max_length=30)),
                ('pres_description', models.TextField(blank=True, null=True)),
                ('pres_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fo_task_preset',
                'ordering': ['title', 'name'],
            },
            bases=('FormikoBot.task',),
        ),
    ]
