# Generated by Django 3.1.5 on 2021-05-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormikoBot', '0006_taskpreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='FormikoBot.Task'),
        ),
    ]
