# Generated by Django 3.1.5 on 2021-06-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormikoBot', '0008_auto_20210527_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettype',
            name='property',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
