# Generated by Django 3.1.5 on 2021-06-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormikoBot', '0009_assettype_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettype',
            name='layerName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
