# Generated by Django 3.1.5 on 2021-06-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormikoBot', '0010_assettype_layername'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='layerName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='property',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
