# Generated by Django 3.1.5 on 2021-09-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormikoBot', '0011_auto_20210601_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='unitprice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
