# Generated by Django 3.1.6 on 2021-02-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormikoBot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='type',
            field=models.CharField(choices=[('PNG', 'PNG Graphic (.png)'), ('JPG', 'JPEG Graphic (.jpg)'), ('VEC', 'Vector Graphic (.ai)'), ('MOV', 'Video (.mov)'), ('HEX', 'Color (Code RGB)'), ('JSON', 'JSON-Data')], default='', max_length=8),
        ),
    ]
