# Generated by Django 3.1.6 on 2021-02-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormikoBot', '0002_auto_20210213_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='json',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
