# Generated by Django 3.1.5 on 2021-02-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormikoBot', '0003_asset_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='type',
            field=models.CharField(choices=[('PNG', 'PNG Graphic (.png)'), ('JPG', 'JPEG Graphic (.jpg)'), ('VEC', 'Vector Graphic (.ai)'), ('MOV', 'Video (.mov)'), ('HEX', 'Color (Code RGB)'), ('FONTNAME', 'Font name'), ('FONTFILE', 'Font file (.ttf)'), ('JSON', 'JSON-Data')], default='', max_length=8),
        ),
    ]
