# Generated by Django 3.1.6 on 2021-02-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormikoBot', '0005_auto_20210226_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assettype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
