# Generated by Django 3.1.6 on 2021-02-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormikoBot', '0006_auto_20210226_2122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assettype',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='assettype',
            name='extention',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
