# Generated by Django 3.1.5 on 2021-03-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormikoBot', '0008_assetpreset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='type',
            new_name='assettype',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='asset',
            name='source',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
