# Generated by Django 3.1.5 on 2021-03-01 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FormikoBot', '0011_auto_20210301_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetpreset',
            old_name='created',
            new_name='pres_created',
        ),
        migrations.RenameField(
            model_name='assetpreset',
            old_name='description',
            new_name='pres_description',
        ),
        migrations.RemoveField(
            model_name='assetpreset',
            name='assettype',
        ),
        migrations.RemoveField(
            model_name='assetpreset',
            name='id',
        ),
        migrations.AddField(
            model_name='assetpreset',
            name='asset_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='FormikoBot.asset'),
            preserve_default=False,
        ),
    ]
