# Generated by Django 3.1.5 on 2021-03-01 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FormikoBot', '0012_auto_20210301_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assettype',
            old_name='extention',
            new_name='extension',
        ),
    ]
