# Generated by Django 3.1.5 on 2021-03-01 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FormikoBot', '0013_auto_20210301_1412'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetpreset',
            options={'ordering': ['title', 'name', 'value']},
        ),
    ]
