# Generated by Django 3.1.5 on 2021-03-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormikoBot', '0016_auto_20210301_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='asset',
            name='value',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True),
        ),
    ]
