# Generated by Django 3.1.5 on 2021-03-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormikoBot', '0017_auto_20210301_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='maxlength',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
