# Generated by Django 3.1.7 on 2021-04-06 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FileCollector', '0002_auto_20210311_1519'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['created']},
        ),
        migrations.RemoveField(
            model_name='video',
            name='description',
        ),
        migrations.RemoveField(
            model_name='video',
            name='title',
        ),
        migrations.RemoveField(
            model_name='video',
            name='version',
        ),
        migrations.AddField(
            model_name='video',
            name='order_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_videos', to='FileCollector.orderproduct'),
        ),
        migrations.AddField(
            model_name='video',
            name='vimeo_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='video',
            name='ffprobe_result',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='response_upload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('FAILED', 'FAILED'), ('COMPLETE', 'COMPLETE')], default='PENDING', max_length=8),
        ),
        migrations.AlterField(
            model_name='video',
            name='unique_fn',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='url_download',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='url_review',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='vimeo_passwd',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
