# Generated by Django 3.1.5 on 2021-04-10 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormikoBot', '0001_initial'),
        ('FileCollector', '0004_auto_20210408_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='assets',
            field=models.ManyToManyField(blank=True, related_name='order_product_assets', to='FormikoBot.Asset'),
        ),
    ]
