# Generated by Django 3.1.7 on 2021-04-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileCollector', '0004_auto_20210407_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='video',
            name='version',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
