# Generated by Django 3.1.6 on 2021-04-16 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FileCollector', '0005_orderproduct_assets'),
        ('FileCollector', '0005_auto_20210409_1224'),
    ]

    operations = [
    ]
