# Generated by Django 3.1.5 on 2021-04-26 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FileCollector', '0005_orderproduct_assets'),
        ('FileCollector', '0005_auto_20210409_1224'),
    ]

    operations = [
    ]
