# Generated by Django 3.1.5 on 2021-04-26 13:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FileCollector', '0006_merge_20210426_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='budget',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='project',
            name='deadline',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='feedbackloops',
            field=models.IntegerField(default='2'),
        ),
        migrations.AddField(
            model_name='project',
            name='paid',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
