# Generated by Django 3.1.5 on 2021-04-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileCollector', '0009_auto_20210426_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=6),
        ),
        migrations.AlterField(
            model_name='project',
            name='paid',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=6),
        ),
    ]
