# Generated by Django 3.1.5 on 2021-04-27 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FileCollector', '0012_auto_20210427_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='intake',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='FileCollector.project'),
        ),
    ]
