# Generated by Django 3.1.5 on 2021-04-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileCollector', '0013_intake_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
