# Generated by Django 3.1.7 on 2021-04-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileCollector', '0014_company_abbreviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='episode',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
