# Generated by Django 3.1.5 on 2021-05-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileCollector', '0016_auto_20210505_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='orderItemID',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
