# Generated by Django 3.1.5 on 2021-05-07 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FileCollector', '0018_auto_20210507_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='orderItemID',
            new_name='orderItemId',
        ),
    ]
