# Generated by Django 3.1.5 on 2021-05-10 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FileCollector', '0006_merge_20210416_1510'),
        ('FileCollector', '0019_auto_20210507_1209'),
    ]

    operations = [
    ]
