# Generated by Django 3.1.5 on 2021-05-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileCollector', '0020_merge_20210510_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='vat_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
