# Generated by Django 3.1.5 on 2021-05-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileCollector', '0021_company_vat_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('ACTIVE', 'ACTIVE'), ('READY', 'READY'), ('FAILED', 'FAILED'), ('COMPLETE', 'COMPLETE'), ('DELIVERED', 'DELIVERED')], default='PENDING', max_length=15),
        ),
    ]
