# Generated by Django 3.1.5 on 2021-05-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileCollector', '0022_auto_20210510_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
