# Generated by Django 3.1.7 on 2021-05-28 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileCollector', '0024_auto_20210525_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='rendering_time',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='size',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
