# Generated by Django 3.1.5 on 2021-05-25 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FileCollector', '0024_auto_20210525_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmanager',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='projectmanager', to=settings.AUTH_USER_MODEL),
        ),
    ]
