# Generated by Django 3.1.5 on 2021-06-01 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FileCollector', '0025_auto_20210528_0911'),
        ('FileCollector', '0025_auto_20210525_1747'),
    ]

    operations = [
    ]
