# Generated by Django 3.1.5 on 2021-06-08 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FileCollector', '0026_merge_20210601_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='FileCollector.project'),
        ),
    ]
