# Generated by Django 3.1.7 on 2021-06-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileCollector', '0027_auto_20210608_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('RENDER', 'RENDER'), ('FAILED', 'FAILED'), ('COMPLETE', 'COMPLETE'), ('IDLE', 'IDLE'), ('READY', 'READY'), ('DELIVERED', 'DELIVERED')], default='PENDING', max_length=15),
        ),
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('UPLOADING', 'UPLOADING'), ('COMPLETE', 'COMPLETE'), ('FAILED', 'FAILED'), ('RENDERING', 'RENDERING')], default='PENDING', max_length=50),
        ),
    ]
