# Generated by Django 3.1.7 on 2021-06-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileCollector', '0028_auto_20210623_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='renderer_job_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
