# Generated by Django 3.1.7 on 2021-06-26 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileCollector', '0029_video_renderer_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('UPLOADING', 'UPLOADING'), ('COMPLETE', 'COMPLETE'), ('FAILED', 'FAILED'), ('RENDERING', 'RENDERING'), ('RENDERING COMPLETE', 'RENDERING COMPLETE'), ('RENDERING FAILED', 'RENDERING FAILED')], default='PENDING', max_length=50),
        ),
    ]
