# Generated by Django 3.1.5 on 2021-09-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormikoBot', '0012_task_unitprice'),
        ('FileCollector', '0031_auto_20210702_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='FormikoBot.Task'),
        ),
    ]
