# Generated by Django 3.1.5 on 2021-09-06 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FileCollector', '0032_project_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intake',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intakes', to='FileCollector.project'),
        ),
    ]
