# Generated by Django 3.1.5 on 2021-09-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileCollector', '0032_project_tasks'),
    ]

    operations = [
        #migrations.AddField(
        #    model_name='project',
        #    name='folderid',
        #    field=models.IntegerField(blank=True, null=True),
        #),
    ]
