# Generated by Django 3.1.5 on 2021-09-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileCollector', '0034_project_folderid'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='estimateid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
