# Generated by Django 3.1.5 on 2021-09-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileCollector', '0036_auto_20210913_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='remark',
            field=models.TextField(blank=True),
        ),
        #migrations.AddField(
        #    model_name='project',
        #    name='folderid',
        #    field=models.IntegerField(blank=True, null=True),
        #),
    ]
