# Generated by Django 3.1.5 on 2021-09-07 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManager', '0002_videoformat'),
        ('FileCollector', '0036_userrole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrole',
            name='default_vimeo_passwd',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='is_bot',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='phone_number',
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=50)),
                ('lastname', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(choices=[('female', 'female'), ('male', 'male'), ('undefined', 'undefined')], default='undefined', max_length=15)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=255)),
                ('default_vimeo_passwd', models.CharField(default='pwd', max_length=100)),
                ('is_bot', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_crew', to='FileCollector.company')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProductManager.language')),
                ('role', models.ManyToManyField(to='FileCollector.UserRole')),
            ],
            options={
                'db_table': 'fo_crew',
            },
        ),
    ]
