# Generated by Django 3.1.5 on 2021-09-07 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManager', '0002_videoformat'),
        ('FileCollector', '0037_auto_20210907_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('unitprice', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('feedbackloops', models.IntegerField(default='2')),
                ('change_log', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_videos', to='FileCollector.order')),
                ('resolution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_resolution', to='ProductManager.resolution')),
                ('videos', models.ManyToManyField(related_name='project_videos', to='FileCollector.Video')),
            ],
            options={
                'db_table': 'fo_project_videos',
            },
        ),
    ]
