# Generated by Django 3.1.5 on 2021-09-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileCollector', '0038_project_folderid'),
    ]

    operations = [
        #migrations.AddField(
        #    model_name='project',
        #    name='folderid',
        #    field=models.IntegerField(blank=True, null=True),
        #),
        migrations.AlterField(
            model_name='file',
            name='filetype',
            field=models.TextField(max_length=6),
        ),
    ]
