# Generated by Django 3.1.5 on 2021-09-07 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FileCollector', '0038_projectvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectvideo',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_videos', to='FileCollector.project'),
        ),
        migrations.AlterField(
            model_name='projectvideo',
            name='videos',
            field=models.ManyToManyField(blank=True, null=True, related_name='project_videos', to='FileCollector.Video'),
        ),
    ]
