# Generated by Django 3.1.5 on 2021-09-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileCollector', '0039_auto_20210907_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='shootingdays',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='projectvideo',
            name='runtime',
            field=models.IntegerField(default='0'),
        ),
    ]
