# Generated by Django 3.1.5 on 2021-09-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileCollector', '0039_auto_20210915_1407'),
    ]

    operations = [
        #migrations.AddField(
        #    model_name='project',
        #    name='folderid',
        #    field=models.IntegerField(blank=True, null=True),
        #),
        migrations.AlterField(
            model_name='file',
            name='filepath',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='file',
            name='filetype',
            field=models.CharField(max_length=6),
        ),
    ]
