# Generated by Django 3.1.5 on 2021-09-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileCollector', '0040_auto_20210915_1409'),
    ]

    operations = [
        #migrations.AddField(
        #    model_name='project',
        #    name='folderid',
        #    field=models.IntegerField(blank=True, null=True),
        #),
        migrations.AlterField(
            model_name='file',
            name='filepath',
            field=models.CharField(max_length=1024),
        ),
    ]
