# Generated by Django 3.1.5 on 2021-09-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileCollector', '0041_auto_20210907_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectvideo',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='project_videos', to='FileCollector.Video'),
        ),
    ]
