# Generated by Django 3.1.5 on 2021-09-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileCollector', '0042_auto_20210907_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmanager',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
    ]
