# Generated by Django 3.1.6 on 2021-10-05 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FileCollector', '0043_projectmanager_is_manager'),
        ('FileCollector', '0042_project_folderid'),
    ]

    operations = [
    ]
