# Generated by Django 3.1.5 on 2021-11-25 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FileCollector', '0044_merge_20211005_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crew',
            name='company',
        ),
        migrations.RemoveField(
            model_name='crew',
            name='created',
        ),
        migrations.RemoveField(
            model_name='crew',
            name='default_vimeo_passwd',
        ),
        migrations.RemoveField(
            model_name='crew',
            name='description',
        ),
        migrations.RemoveField(
            model_name='crew',
            name='email',
        ),
        migrations.RemoveField(
            model_name='crew',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='crew',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='crew',
            name='is_bot',
        ),
        migrations.RemoveField(
            model_name='crew',
            name='language',
        ),
        migrations.RemoveField(
            model_name='crew',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='crew',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='crew',
            name='updated',
        ),
        migrations.AddField(
            model_name='crew',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crew_person', to='FileCollector.projectmanager'),
        ),
        migrations.AddField(
            model_name='crew',
            name='remark',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.RemoveField(
            model_name='crew',
            name='role',
        ),
        migrations.AddField(
            model_name='crew',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FileCollector.userrole'),
        ),
    ]
