# Generated by Django 3.1.5 on 2021-11-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileCollector', '0045_auto_20211126_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='shootingdays',
            field=models.DecimalField(decimal_places=1, default='0', max_digits=6),
        ),
    ]
