# Generated by Django 3.1.5 on 2021-11-30 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManager', '0002_videoformat'),
        ('FileCollector', '0046_auto_20211129_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_languages', to='ProductManager.language'),
        ),
        migrations.AddField(
            model_name='video',
            name='sub_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtitle_languages', to='ProductManager.language'),
        ),
    ]
