# Generated by Django 3.1.5 on 2021-12-03 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManager', '0002_videoformat'),
        ('FileCollector', '0048_auto_20211203_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='bitrate',
            field=models.BigIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='codec_long_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='video',
            name='codec_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='video',
            name='fps',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='pix_fmt',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='video',
            name='resolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_resolution', to='ProductManager.resolution'),
        ),
        migrations.AlterField(
            model_name='projectvideo',
            name='resolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projectvideo_resolution', to='ProductManager.resolution'),
        ),
    ]
