# Generated by Django 3.1.6 on 2022-01-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileCollector', '0049_auto_20211203_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectvideo',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
