# Generated by Django 3.1.6 on 2022-01-17 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManager', '0007_language_system_language'),
        ('FileCollector', '0050_auto_20220116_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectvideo',
            name='episode',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectvideo',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prokectvideo_languages', to='ProductManager.language'),
        ),
        migrations.AddField(
            model_name='projectvideo',
            name='sub_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projectvideo_subtitle_languages', to='ProductManager.language'),
        ),
    ]
