# Generated by Django 3.1.6 on 2022-01-18 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FileCollector', '0051_auto_20220117_1909'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectvideo',
            options={'ordering': ['-created']},
        ),
    ]
