# Generated by Django 3.1.6 on 2021-02-12 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManager', '0003_auto_20210208_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbase',
            name='needs_intake',
            field=models.BooleanField(default=False),
        ),
    ]
