# Generated by Django 3.1.6 on 2021-02-12 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManager', '0004_productbase_needs_intake'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbase',
            name='needs_json',
            field=models.BooleanField(default=False),
        ),
    ]
