# Generated by Django 3.1.6 on 2021-02-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormikoBot', '0003_asset_json'),
        ('ProductManager', '0005_productbase_needs_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbase',
            name='assets',
            field=models.ManyToManyField(blank=True, related_name='product_assets', to='FormikoBot.Asset'),
        ),
    ]
