# Generated by Django 3.1.6 on 2021-02-13 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManager', '0006_productbase_assets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbase',
            name='needs_json',
        ),
    ]
