# Generated by Django 3.1.5 on 2021-02-17 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManager', '0007_remove_productbase_needs_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='resolution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ProductManager.resolution'),
        ),
    ]
