# Generated by Django 3.1.5 on 2021-02-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManager', '0008_auto_20210217_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rendertime',
            field=models.IntegerField(default='0'),
        ),
    ]
