# Generated by Django 3.1.7 on 2022-01-01 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManager', '0003_auto_20211228_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='name',
        ),
        migrations.AlterField(
            model_name='productimagetext',
            name='desc_long',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='productimagetext',
            name='desc_short',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='productimagetext',
            name='product_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_image_texts', to='ProductManager.productimage'),
        ),
        migrations.AlterField(
            model_name='producttext',
            name='desc_long',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='producttext',
            name='desc_short',
            field=models.TextField(blank=True),
        ),
    ]
