# Generated by Django 3.1.6 on 2022-01-12 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManager', '0004_auto_20220101_1752'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['display_order']},
        ),
    ]
