# Generated by Django 3.1.6 on 2022-01-13 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManager', '0005_auto_20220112_2317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['name']},
        ),
    ]
