# Generated by Django 3.1.4 on 2021-01-28 20:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=50)),
                ('lastname', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('abbreviation', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'fo_client',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('street', models.CharField(blank=True, max_length=256)),
                ('zip_code', models.CharField(blank=True, max_length=256)),
                ('place', models.CharField(blank=True, max_length=256)),
                ('country', models.CharField(blank=True, max_length=256)),
                ('website', models.TextField(blank=True)),
                ('phone_number', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'db_table': 'fo_company',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('filepath', models.CharField(max_length=255)),
                ('filetype', models.CharField(max_length=6)),
                ('size', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fo_files',
            },
        ),
        migrations.CreateModel(
            name='Intake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.EmailField(max_length=254)),
                ('change_log', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fo_intake',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(choices=[('FSP', 'SHOP'), ('MAN', 'MANUAL')], default='FSP', max_length=8)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('ACTIVE', 'ACTIVE'), ('FAILED', 'FAILED'), ('COMPLETE', 'COMPLETE'), ('DELIVERED', 'DELIVERED')], default='PENDING', max_length=15)),
                ('shop_order_id', models.IntegerField(blank=True, db_column='SHOP_ORDER_ID', null=True)),
                ('shop_unique_token', models.CharField(blank=True, db_column='SHOP_UNIQUE_TOKEN', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fo_order',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_vimeo_passwd', models.CharField(default='pwd', max_length=100)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('abbreviation', models.CharField(max_length=10, unique=True)),
                ('change_log', models.TextField()),
                ('video_target_width', models.IntegerField(default='1280')),
                ('video_target_height', models.IntegerField(default='720')),
                ('video_target_size', models.IntegerField(default='2')),
                ('video_target_duration', models.DurationField(default=datetime.timedelta(seconds=1))),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FileCollector.client')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FileCollector.company')),
            ],
            options={
                'db_table': 'fo_project',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(max_length=25)),
                ('vimeo_passwd', models.CharField(max_length=100)),
                ('url', models.TextField()),
                ('url_review', models.TextField()),
                ('url_download', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('ACTIVE', 'ACTIVE'), ('FAILED', 'FAILED'), ('COMPLETE', 'COMPLETE')], default='PENDING', max_length=8)),
                ('unique_fn', models.CharField(max_length=255)),
                ('ffprobe_result', models.JSONField(null=True)),
                ('response_upload', models.JSONField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='FileCollector.project')),
            ],
            options={
                'db_table': 'fo_video',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='VimeoResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=255)),
                ('response_text', models.JSONField(null=True)),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vimeo_responses', to='FileCollector.video')),
            ],
            options={
                'db_table': 'fo_vimeoresponse',
            },
        ),
        migrations.CreateModel(
            name='ProjectManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=50)),
                ('lastname', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fo_person',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='project',
            name='projectmanager',
            field=models.ManyToManyField(to='FileCollector.ProjectManager'),
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('ACTIVE', 'ACTIVE'), ('FAILED', 'FAILED'), ('COMPLETE', 'COMPLETE'), ('IDLE', 'IDLE'), ('READY', 'READY')], default='PENDING', max_length=15)),
                ('json', models.JSONField(blank=True, null=True)),
                ('change_log', models.TextField(blank=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='FileCollector.order')),
            ],
            options={
                'db_table': 'fo_order_products',
            },
        ),
    ]
