# Generated by Django 3.1.4 on 2021-01-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileCollector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('ACTIVE', 'ACTIVE'), ('FAILED', 'FAILED'), ('COMPLETE', 'COMPLETE')], default='PENDING', max_length=8),
        ),
    ]
