# Generated by Django 3.1.4 on 2021-01-28 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProductManager', '0001_initial'),
        ('FormikoBot', '0001_initial'),
        ('FileCollector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductManager.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='FileCollector.client'),
        ),
        migrations.AddField(
            model_name='intake',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FileCollector.order'),
        ),
        migrations.AddField(
            model_name='file',
            name='intake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='FileCollector.intake'),
        ),
        migrations.AddField(
            model_name='company',
            name='assets',
            field=models.ManyToManyField(blank=True, related_name='company_assets', to='FormikoBot.Asset'),
        ),
        migrations.AddField(
            model_name='client',
            name='assets',
            field=models.ManyToManyField(blank=True, related_name='client_assets', to='FormikoBot.Asset'),
        ),
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_clients', to='FileCollector.company'),
        ),
    ]
