# Generated by Django 3.1.4 on 2021-01-04 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManager', '0029_auto_20210104_2123'),
        ('FileCollector', '0002_orderproduct_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductManager.product'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
