# Generated by Django 3.1.4 on 2021-01-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileCollector', '0003_auto_20210129_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='default_vimeo_passwd',
            field=models.CharField(default='pwd', max_length=100),
        ),
        migrations.AddField(
            model_name='projectmanager',
            name='default_vimeo_passwd',
            field=models.CharField(default='pwd', max_length=100),
        ),
    ]
