# Generated by Django 3.1.4 on 2021-01-04 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FileCollector', '0003_auto_20210104_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intake',
            name='order',
        ),
    ]
