# Generated by Django 3.1.4 on 2021-01-04 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FileCollector', '0004_remove_intake_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='intake',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='FileCollector.order'),
            preserve_default=False,
        ),
    ]
