# Generated by Django 3.1.5 on 2021-02-08 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FileCollector', '0006_company_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intake',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FileCollector.order'),
        ),
    ]
