# Generated by Django 3.1.5 on 2021-02-08 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileCollector', '0007_auto_20210208_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='shop_customer_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='origin',
            field=models.CharField(choices=[('FSP', 'FSP'), ('MAN', 'MANUAL')], default='FSP', max_length=8),
        ),
    ]
