# Generated by Django 3.1.5 on 2021-02-08 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManager', '0002_auto_20210202_1746'),
        ('FileCollector', '0008_auto_20210208_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='client',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProductManager.language'),
        ),
        migrations.AlterField(
            model_name='company',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProductManager.language'),
        ),
    ]
