# Generated by Django 3.1.5 on 2021-02-08 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileCollector', '0009_auto_20210208_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='change_log',
            field=models.TextField(blank=True),
        ),
    ]
