# Generated by Django 3.1.5 on 2021-02-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileCollector', '0010_order_change_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='shop_username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
