# Generated by Django 3.1.5 on 2021-02-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileCollector', '0010_order_change_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('ACTIVE', 'ACTIVE'), ('FAILED', 'FAILED'), ('COMPLETE', 'COMPLETE'), ('IDLE', 'IDLE'), ('READY', 'READY'), ('DELIVERED', 'DELIVERED')], default='PENDING', max_length=15),
        ),
    ]
