# Generated by Django 3.1.5 on 2021-02-12 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FileCollector', '0011_auto_20210210_1207'),
        ('FileCollector', '0012_auto_20210211_1442'),
    ]

    operations = [
    ]
