# Generated by Django 3.1.5 on 2021-02-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileCollector', '0013_merge_20210212_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_reference_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
