# Generated by Django 3.1.6 on 2021-02-12 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FileCollector', '0016_auto_20210212_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='placed',
        ),
    ]
