# Generated by Django 3.1.6 on 2021-02-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileCollector', '0017_remove_order_placed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='placed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
