# Generated by Django 3.1.5 on 2021-02-15 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FileCollector', '0018_order_placed'),
    ]

    operations = [
        migrations.AddField(
            model_name='intake',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='FileCollector.client'),
        ),
    ]
