# Generated by Django 3.1.5 on 2021-02-15 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FileCollector', '0019_intake_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intake',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='FileCollector.client'),
        ),
        migrations.AlterField(
            model_name='intake',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FileCollector.order'),
        ),
    ]
