# Generated by Django 3.1.5 on 2021-02-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileCollector', '0021_intake_shop_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intake',
            name='shop_order_id',
            field=models.IntegerField(blank=True, db_column='SHOP_ORDER_ID', null=True),
        ),
    ]
