# Generated by Django 3.1.6 on 2021-02-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileCollector', '0022_auto_20210215_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
