# Generated by Django 3.1.6 on 2021-02-20 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileCollector', '0023_order_fid'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolderIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
