# Generated by Django 3.1.5 on 2021-02-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileCollector', '0024_folderindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='unitprice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
