# Generated by Django 3.1.5 on 2021-09-06 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FileCollector', '0035_project_estimateid'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.DecimalField(decimal_places=0, default=0, max_digits=5)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('change_log', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('PAID', 'PAID'), ('DISCOUNTED', 'DISCOUNTED')], default='PENDING', max_length=15)),
                ('paid', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineitems', to='FileCollector.project')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='FileCollector.video')),
            ],
            options={
                'db_table': 'fo_lineitem',
            },
        ),
    ]
