# Generated by Django 3.1.5 on 2021-09-07 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FileCollector', '0035_project_estimateid'),
        ('ProductManager', '0002_videoformat'),
        ('FormikoAudit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startime', models.DateTimeField(blank=True, null=True)),
                ('endtime', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=250)),
                ('damages', models.TextField(blank=True)),
                ('remark', models.TextField(blank=True)),
                ('change_log', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shoots', to='FileCollector.project')),
            ],
            options={
                'db_table': 'fo_shoot',
            },
        ),
        migrations.CreateModel(
            name='CameraSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whitebalance', models.DecimalField(decimal_places=0, default=5600, max_digits=4)),
                ('framerate', models.DecimalField(decimal_places=0, default=25, max_digits=4)),
                ('camera', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('colorprofile', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('videoformat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videoformats', to='ProductManager.videoformat')),
            ],
        ),
    ]
