# Generated by Django 3.1.5 on 2021-09-07 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FileCollector', '0036_userrole'),
        ('FormikoAudit', '0002_camerasetting_shoot'),
    ]

    operations = [
        migrations.AddField(
            model_name='camerasetting',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camerasettings', to='FileCollector.userrole'),
        ),
        migrations.AddField(
            model_name='shoot',
            name='crew',
            field=models.ManyToManyField(blank=True, related_name='shoots', to='FileCollector.UserRole'),
        ),
    ]
