# Generated by Django 3.1.5 on 2021-09-07 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FormikoAudit', '0003_auto_20210907_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoot',
            old_name='startime',
            new_name='starttime',
        ),
    ]
