# Generated by Django 3.1.5 on 2021-09-07 08:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FormikoAudit', '0004_auto_20210907_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='camerasetting',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camerasetting',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='camerasetting',
            table='fo_camerasetting',
        ),
    ]
