# Generated by Django 3.1.5 on 2021-09-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileCollector', '0037_auto_20210907_1048'),
        ('FormikoAudit', '0005_auto_20210907_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoot',
            name='crew',
            field=models.ManyToManyField(blank=True, related_name='shoots', to='FileCollector.Crew'),
        ),
    ]
