# Generated by Django 3.1.5 on 2021-09-07 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FileCollector', '0037_auto_20210907_1048'),
        ('FormikoAudit', '0007_auto_20210907_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camerasetting',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camera_operator', to='FileCollector.crew'),
        ),
    ]
