# Generated by Django 3.1.5 on 2021-09-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormikoAudit', '0008_auto_20210907_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoot',
            name='settings',
        ),
        migrations.AddField(
            model_name='shoot',
            name='settings',
            field=models.ManyToManyField(related_name='shoot_settings', to='FormikoAudit.CameraSetting'),
        ),
    ]
