# Generated by Django 3.1.5 on 2021-09-08 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FileCollector', '0043_projectmanager_is_manager'),
        ('FormikoAudit', '0010_lineitem_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoot',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FileCollector.projectmanager'),
        ),
        migrations.AlterField(
            model_name='shoot',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_shoots', to='FileCollector.project'),
        ),
    ]
