# Generated by Django 3.1.5 on 2021-09-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormikoAudit', '0011_auto_20210908_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='camerasetting',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shoot',
            name='change_log',
            field=models.TextField(blank=True, null=True),
        ),
    ]
